# Generated by Django 4.2.13 on 2024-05-14 14:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_data_for_schools"),
    ]

    operations = [
        migrations.AddField(
            model_name="gamingsession",
            name="school",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="api.school",
            ),
            preserve_default=False,
        ),
    ]
