# Generated by Django 4.2.13 on 2024-06-27 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_gamingsession_school"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamingsession",
            name="grade",
            field=models.CharField(max_length=5),
        ),
    ]
