# Generated by Django 4.2.13 on 2024-06-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0006_alter_gamingsession_grade"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gamingsession",
            name="grade",
            field=models.CharField(max_length=6),
        ),
    ]
